### ISSUE TITLE
Iframe unable to access the cookies set by the popped out auth window 

### ISSUE THREAD

**Issue by parthiiita** [privacysandbox/privacy-sandbox-dev-support#264] opened 2024-02-27 00:40 UTC
Hi Team,
Some of the third party apps in microsoft teams which are rendered inside an iframe in teams are experienceing breaking of their auth flow which is trigerred in a popped out window, and on succesful authentication auth related cookies are set in the popup with atrributes sameSite:none and unpartitioned. These cookies are expected to be accesible by the iframe , but they are not, please find the below scenario via a custom cookie app we developed-

we are unable to access unpartitioned SameSite:none cookies set by a popped out tab in the app iframe in teams , whereas with 3p cookies blocking disabled we can access these.

popped out tab cookie c1:v1 unpartitioned sameSite:None 
![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/24573328/7838d074-f70b-441f-acc7-fa202b862d85)

App iframe , c1:v1 not available with 3p cookies blocking enabled
![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/24573328/1db2ae6d-d460-4d6c-800d-ef5675957e66)

With 3p cookies blocking disabled c1:v1 is available to app iframe 
![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/24573328/9282ef79-43f8-4794-9957-d605908f9545)

Please provide what is the guidance to handle such authentication scenarios as its breaking authentication for apps like Lucidcharts etc in teams.

Thanks

**Comment by parthiiita** [comment] 2024-03-01 16:10
Hi @amaliev , below is a link to the video repro of the issue with instructions in the video as well as below:

https://drive.google.com/file/d/1lifkm2KJjCzP80bwsq4w30A64YyievEI/view?usp=sharing

Here are the instructions to repro the issue:
Disable 3p cookies in your browser.
open [teams.microsoft.com](https://www.google.com/url?q=http://teams.microsoft.com&sa=D&source=buganizer&usg=AOvVaw379MuuoNQsAHG2UN_mjAsj)
click on try new teams toggle on the top left
click on + apps icon in left rail and then click manage your apps
click on lucid charts and click on sign in in lucid charts iframe
use any external auth in the popped out sign in page
post authentication, observe that lucid charts redirects to sign in page and no cookies are sent on the original url that was opened, this can be seen in the network tab
Please use the following credentials to login into teams
email:
 
[admin@M365B125723.onmicrosoft.com](mailto:admin@M365B125723.onmicrosoft.com)
 
password:
 
7f#j(fNM5F73nC%(


Please let me know in case you need any more details to repro the issue.

Thanks
Parth

**Comment by amaliev** [comment] 2024-03-01 19:29
Hi @parthiiita , I have reproduced these steps in Chrome, and the Chrome implementation of the popup heuristic handles this case successfully.

With heuristics enabled (as described in the [testing instructions](https://github.com/amaliev/3pcd-exemption-heuristics/blob/main/explainer.md#testing-instructions)):
![teams_with_popup_heuristic](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/21073645/81f3ba28-05f5-4bfe-82bf-b0c1baaf204c)

With heuristics disabled (as described in the [testing instructions](https://github.com/amaliev/3pcd-exemption-heuristics/blob/main/explainer.md#testing-instructions)):
![teams_without_popup_heuristic](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/21073645/09213e0a-be1c-4e4d-bd1e-4d82ed853afe)

I've confirmed that completing the login flow for lucid.app creates a 3PC access grant for `https://[*.]lucid.app` when embedded on `https://[*.]microsoft.com`.

**Comment by parthiiita** [comment] 2024-05-07 17:51
Hi @amaliev , thanks for the explanation, Is heuristics a short term mitigation of the impact of the 3p cookies deprecation or Heuristics will always be supported when the 3P cookie deprecation rolls out, can we rely on Heuristics as a solution for long term ?

**Comment by amaliev** [comment] 2024-05-08 17:22
Heuristics is intended as a short-term mitigation. To handle this use case in the long term, I would recommend adopting one of the privacy-preserving APIs listed [here](https://developers.google.com/privacy-sandbox/3pcd/prepare/prepare-for-phaseout#take_action_to_ensure_your_sites_are_prepared).

**Comment by parthiiita** [comment] 2024-05-20 22:43
Hi @amaliev , what is the timeline for the heuristics deprecation? Is it going to be disabled soon after January 2025, or it will be disabled in second half of 2025? We want to know how soon we need to be ready with the heuristics disabled and how long can we rely on that ?

**Comment by amaliev** [comment] 2024-05-21 15:25
Hi @parthiiita . We don't have a strict timeline for deprecating heuristics for now - this will require ongoing discussions with web standards.

**Comment by amaliev** [comment] 2024-07-16 17:00
I will close this issue as we have not been able to reproduce it in the Chrome browser (since it is mitigated by the popup heuristic). If you see this issue reappear, could you please file a breakage report at https://goo.gle/report-3pc-broken? Thank you!

**Closed** 2024-07-18 18:15 UTC
Labels: third-party-cookie-deprecation
